- README.md
- cassandra/README.md
- cassandra/project.clj
- cassandra/src/cassandra/batch.clj
- cassandra/src/cassandra/checker.clj
- cassandra/src/cassandra/collections/map.clj
- cassandra/src/cassandra/collections/set.clj
- cassandra/src/cassandra/conductors.clj
- cassandra/src/cassandra/core.clj
- cassandra/src/cassandra/counter.clj
- cassandra/src/cassandra/lwt.clj
- cassandra/src/cassandra/nemesis.clj
- cassandra/src/cassandra/runner.clj
- cassandra/test/cassandra/cassandra_test.clj
- scalardb/README.md
- scalardb/project.clj
- scalardb/src/scalardb/core.clj
- scalardb/src/scalardb/runner.clj
- scalardb/src/scalardb/transfer.clj
- scalardb/src/scalardb/transfer_append.clj
- scalardb/test/scalardb/scalardb_test.clj
Just copy files from `scalar-labs/jepsen/cassandra` and `scalar-labs/scalardb/jepsen/scalardb`
I've checked if I can run tests with Jepsen docker in https://github.com/jepsen-io/jepsen.
I wrote how to run in the new `README.md`.
> Copy Jepsen tests for Cassandra and Scalar DB

- cassandra/src/cassandra/nemesis.clj
https://scalar-labs.atlassian.net/browse/DLT-3250
The checking should care about decommissioned nodes
> fix checking dead nodes

- scalardb/src/scalardb/core.clj
- scalardb/test/scalardb/core_test.clj
https://scalar-labs.atlassian.net/browse/DLT-2749
- Refine service creation by uniforming storage and transaction service creation
- Add unit tests for `scalardb.core`
> Refine service creation & Add unit tests for core

- cassandra/src/cassandra/core.clj
- cassandra/test/cassandra/core_test.clj
- scalardl/src/scalardl/core.clj
- Remove specifying `debian/os` since some packages have been installed
- It just installs some packages
- Add `apt-get update` when JDK install failed
- According to my investigation, JDK install failed when some dependent packages are old. After retrying `apt-get update`, it works well.
> add apt update

- cassandra/src/cassandra/nemesis.clj
- cassandra/test/cassandra/nemesis_test.clj
https://scalar-labs.atlassian.net/browse/DLT-4207
When the first seed node was decommissioned, some non-seed nodes couldn't restart.
Another seed must restart at first in this situation.
- Choose a seed except for the decommissioned nodes
- Modify a unit test for this situation
> fix C* restart order

- cassandra/project.clj
- scalardb/project.clj
- scalardl/project.clj
I want to upgrade Jepsen.
We had an error of wget. jepsen.control.util/wget retries since 0.1.14. 
Ref. https://github.com/jepsen-io/jepsen/releases
> Upgrade Jepsen to 0.1.15

- cassandra/src/cassandra/batch.clj
- cassandra/src/cassandra/collections/map.clj
- cassandra/src/cassandra/collections/set.clj
- cassandra/src/cassandra/core.clj
- cassandra/src/cassandra/counter.clj
- cassandra/src/cassandra/lwt.clj
- cassandra/test/cassandra/batch_test.clj
- cassandra/test/cassandra/core_test.clj
- cassandra/test/cassandra/counter_test.clj
- cassandra/test/cassandra/lwt_test.clj
- cassandra/test/cassandra/map_test.clj
- cassandra/test/cassandra/set_test.clj
https://scalar-labs.atlassian.net/browse/DLT-4376
- Move exception handling to `cassandra/core.clj`
- Handle TransportException
- Jepsen checker failed because this exception wasn't handled properly
- Handle WriteTimeoutException
- Check WriteType for recognizing the write can be applied
- Reduce `:info` type which takes a long time to check the consistency
> Handle TransportException and WriteTimeoutException

- cassandra/src/cassandra/batch.clj
A test failed when a batch write was delayed by network failure.
https://scalar-labs.atlassian.net/browse/DLT-4416
- Waits for batchlog reply before reading all records
> Wait for batchlog replay

- cassandra/src/cassandra/batch.clj
- cassandra/src/cassandra/collections/map.clj
- cassandra/src/cassandra/collections/set.clj
- cassandra/src/cassandra/lwt.clj
https://scalar-labs.atlassian.net/browse/DLT-4572
`TransportException` couldn’t be caught when a session tries `use-keyspace` failed.
> catch TransportException when use-keyspace fails

- cassandra/src/cassandra/collections/map.clj
- cassandra/src/cassandra/collections/set.clj
- cassandra/src/cassandra/counter.clj
https://scalar-labs.atlassian.net/browse/DLT-4623
https://scalar-labs.atlassian.net/browse/DLT-4626
Delayed writes issue happened.
The batch tests failed due to the same issue.
It has been fixed by #26.
In my investigation, the wait is required for other tests, too.
> Add a wait before the read phase

- cassandra/src/cassandra/core.clj
- cassandra/src/cassandra/counter.clj
- cassandra/src/cassandra/lwt.clj
- cassandra/test/cassandra/core_test.clj
- cassandra/test/cassandra/counter_test.clj
https://scalar-labs.atlassian.net/browse/DLT-4646
https://scalar-labs.atlassian.net/browse/DLT-4650
In the counter test, after WriteTimeoutException, some values had been applied eventually.
However, all results were `:fail` when WriteTimeoutException in the counter test.
I want to fix this error handling to return `:info` because a value might be applied eventually.
And, I remove the unneeded retry for the counter write.
Retry operation is complicated and the unexpected exception should be removed.
> Return :info when WriteTimeoutException for counter write

- scalardl/src/scalardl/core.clj
https://scalar-labs.atlassian.net/browse/DLT-4778
Certificate registration failed after https://github.com/scalar-labs/scalar/pull/343 because `ClientService#registerCertificate()` doesn't return a response.
- Check `ClientException` when registration fails
> Fix error handling for certificate and contract registration

- cassandra/src/cassandra/core.clj
- cassandra/test/cassandra/core_test.clj
https://scalar-labs.atlassian.net/browse/DLT-4785
In the counter test, some counter writes had applied values when TransportException (a node is down).
- Change the result from `:fail` to `:info` when TransportException.
> change the result to :info when TransportException

- scalardb/project.clj
- scalardl/project.clj
https://scalar-labs.atlassian.net/browse/DLT-6296
Cause: C* test uses Jepsen `0.1.18`, but DB and DL tests use `0.1.15`
> update jepsen for DB and DL

- cassandra/src/cassandra/core.clj
https://scalar-labs.atlassian.net/browse/DLT-6333
For `fressian` writing the history to a fressian file, it is impossible to write an Exception.
> Get a message from an exception

- scalardl/src/scalardl/core.clj
https://scalar-labs.atlassian.net/browse/DLT-6435
https://scalar-labs.atlassian.net/browse/DLT-6433
I found the root cause of test failures.
An option `-config` of a DL server was updated last week. However, I didn't update that.
I didn't have to add retry for DL tests. But I don't want to revert because it is helpful when the network is unstable.
> Fix DL server option

- scalardb/src/scalardb/transfer.clj
- scalardl/src/scalardl/transfer.clj
https://scalar-labs.atlassian.net/browse/DLT-6462
https://scalar-labs.atlassian.net/browse/DLT-6463
https://scalar-labs.atlassian.net/browse/DLT-6493
These failures were caused by write delay for the transaction states.
I think it is better to check the coordinator.state table after getting all balances.
That's because an unknown state will be fixed by getting each balance.
> check transaction states after getting all balances

- scalardl/src/scalardl/cas.clj
- scalardl/src/scalardl/cassandra.clj
- scalardl/src/scalardl/core.clj
- scalardl/src/scalardl/transfer.clj
- scalardl/test/scalardl/cas_test.clj
- scalardl/test/scalardl/cassandra_test.clj
- scalardl/test/scalardl/transfer_test.clj
https://scalar-labs.atlassian.net/browse/DLT-6558
Issue:
- When ABORTED state exists or the state doesn't exist, the count of committed transactions was wrong
Cause:
- When ABORTED state exists or the state doesn't exist, `check-tx-committed` throws an exception
- No exception was thrown in `check-tx-state`
Fix:
- `check-tx-state?` can throw an exception when the read fails
- `check-tx-committed` can returns `false`
- `retry-when-exception` can throw an exception when the last failure
- Some unit tests are modified and added
> Fix check-tx-state

- scalardl/project.clj
https://scalar-labs.atlassian.net/browse/DLT-7162
The test failed due to the incompatible gRPC version.
The gRPC version of Scalar DLT has been updated at https://github.com/scalar-labs/scalar/pull/504.
> Update gRPC version

- scalardb/src/scalardb/core.clj
- scalardb/src/scalardb/transfer.clj
- scalardb/src/scalardb/transfer_append.clj
- scalardb/test/scalardb/transfer_append_test.clj
- scalardb/test/scalardb/transfer_test.clj
https://scalar-labs.atlassian.net/browse/DLT-7801
DB Jepsen test failed frequently when the network was unstable.
I want to add retries to the population phase in the DB tests.
> Retry DB population when exception

- cassandra/project.clj
- scalardb/README.md
- scalardb/project.clj
- scalardb/src/scalardb/core.clj
- scalardb/src/scalardb/elle_append.clj
- scalardb/src/scalardb/runner.clj
- scalardb/test/scalardb/core_test.clj
- scalardb/test/scalardb/elle_append_test.clj
- scalardl/project.clj
To verify serializable transactions: https://scalar-labs.atlassian.net/browse/DLT-6513
The current Scalar DB (2.4.0) using snapshot isolation (also in the case using serializable) failed in this test because a transaction could read a different value after another transaction committed.
https://scalar-labs.atlassian.net/browse/DLT-7969
> Add elle-append test

- scalardb/src/scalardb/elle_append.clj
- scalardb/test/scalardb/elle_append_test.clj
I found that `sk` column isn't required for the `elle-append` test though I referred to the existing test which added the column.
> Remove sk column from elle-append

- scalardb/project.clj
- scalardb/src/scalardb/elle_write_read.clj
- scalardb/src/scalardb/runner.clj
- scalardb/test/scalardb/elle_write_read_test.clj
https://scalar-labs.atlassian.net/browse/DLT-6513
To add a new test with `jepsen.tests.cycle.wr`.
This test is simpler than `elle-append` test.
In the test, a transaction just inserts or updates the value of the `val` column instead of appending, and the check phase checks the consistency.
> add write-read-test

- scalardl/project.clj
https://scalar-labs.atlassian.net/browse/DLT-8227
The test failed because `./gradlew clientJar` didn't work anymore.
I replaced the jar file.
> replace client.jar

- scalardl/src/scalardl/core.clj
https://scalar-labs.atlassian.net/browse/DLT-8313
When the JDK installation failed, a test failed because `fallback` wasn't executed.
The cause is that `fallback` is given as a vector.
I fixed it by giving `fallback` as it is.
> Fix to do fallback

- scalardl/project.clj
- scalardl/test/scalardl/cas_test.clj
- scalardl/test/scalardl/transfer_test.clj
Scalar dl common, rpc and java client sdk are updated. 
Dependent PR: https://github.com/scalar-labs/scalar/pull/617
> Update scalar jepsen test with latest scalar dl

- scalardb/src/scalardb/core.clj
- scalardb/src/scalardb/runner.clj
- scalardb/test/scalardb/core_test.clj
The serializable strategy property name is changed from Scalar DB 3.0. This PR changes it. Please take a look!
> Correct the serializable strategy property name

- scalardb/project.clj
- scalardb/src/scalardb/core.clj
- scalardb/src/scalardb/elle_append.clj
- scalardb/src/scalardb/elle_append_2pc.clj
- scalardb/src/scalardb/elle_write_read.clj
- scalardb/src/scalardb/elle_write_read_2pc.clj
- scalardb/test/scalardb/elle_append_2pc_test.clj
- scalardb/test/scalardb/elle_append_test.clj
- scalardb/test/scalardb/elle_write_read_2pc_test.clj
- scalardb/test/scalardb/elle_write_read_test.clj
To avoid the OOM issue and make the running time short, I applied `independent` to the Elle tests.
An `independent` test increments the sequence number per a fixed number of transactions. The test adds tables in advance during the execution and makes transactions of the next sequence access the new tables.
We could refactor almost the same functions. I'll do that in another PR.
> Apply `independent` to the elle tests

- cassandra/src/cassandra/core.clj
- cassandra/src/cassandra/nemesis.clj
Check the readiness of each C* node instead of just sleeping
> Check C* readiness

- scalardb/src/scalardb/elle_append.clj
- scalardb/src/scalardb/elle_append_2pc.clj
- scalardb/src/scalardb/elle_write_read.clj
- scalardb/src/scalardb/elle_write_read_2pc.clj
When table creation failure happened in Elle tests, the exception wasn't caught in the `invoke!` operation and the error couldn't be understood by the result writer.
The exception for table creation failure should be caught and return the `op` with the error message in the `invoke!`.
> catch failure of adding tables

- scalardb/src/scalardb/core.clj
- scalardb/src/scalardb/transfer.clj
- scalardb/src/scalardb/transfer_2pc.clj
- scalardb/test/scalardb/transfer_2pc_test.clj
- scalardb/test/scalardb/transfer_test.clj
After the change in [scalar-labs/scalardb#428](https://github.com/scalar-labs/scalardb/pull/428), we can't get the transactional meta columns from Transaction API. To get the transactional meta columns, we need to use Storage API. This PR fixes this issue. Please take a look!
> Fix read record for checker

- cassandra/src/cassandra/core.clj
- cassandra/src/cassandra/nemesis.clj
- scalardl/src/scalardl/cassandra.clj
- scalardl/src/scalardl/core.clj
Issue:
In the DL tests, the reordering to restart C* nodes didn't work when all C* nodes were down
Fix:
Use `:cass-nodes` if it is set
> check :cass-nodes

- scalardl/src/scalardl/cassandra.clj
- scalardl/src/scalardl/core.clj
The DL server nodes failed to wait for Cassandra nodes.
Cause:
A DL server node didn't have `cqlsh` command and always failed to try to execute it because a test doesn't install Cassandra to the DL server node.
Fix:
A DL server node waits for Cassandra nodes for the fixed time without `cqlsh`
> [DL] wait Cassandra nodes for the fixed time

- scalardl/project.clj
- scalardl/test/scalardl/cas_test.clj
- scalardl/test/scalardl/transfer_test.clj
Update the `protobuf` version to 3.19.2 based on https://github.com/scalar-labs/scalar/pull/758 and update `scalardl-java-client-sdk` version to 3.3.1.
> Update scalardl-java-client-sdk and protobuf version

- scalardb/src/scalardb/transfer.clj
- scalardb/src/scalardb/transfer_2pc.clj
It looks like in the `transfer` test, before prefixed columns are created for primary key columns, which is unexpected behavior. This PR fixes this bug. Please take a look!
> Should not create before prefixed columns for primary key columns

- scalardl/project.clj
Updated project.clj file to use snapshot versions for scalardl-java-client-sdk.
> Updated dependencies to use snapshot versions

- scalardl/src/scalardl/transfer.clj
- scalardl/test/scalardl/transfer_test.clj
Basically the same fix as [this](https://github.com/scalar-labs/kelpie-test/pull/60).
This introduced the recent `Invalid analysis` error since a nonce given from a client is not used as a transaction ID in the server; thus, the nonce cannot be found in the coordinator table.
> Fix the way to pass nonce (txid) since the current way is unofficial

- scalardl/src/scalardl/nemesis.clj
In Jepsen tests of Cassandra and Scalar DB, each node should wait for readiness.
However, the tests of DL didn’t because the nemesis is not the same as that of Cassandra and Scalar DB.
> Wait for node readiness in DL tests

- scalardb/project.clj
Because we are facing a `Guava` version conflict issue, this PR upgrades `Guava` to `31.1-jre`. Please take a look!
> Update Guava to 31.1-jre

- scalardb/project.clj
- scalardb/src/scalardb/core.clj
- scalardb/test/scalardb/core_test.clj
After the change in https://github.com/scalar-labs/scalardb/pull/715, we need to create a two-phase commit transaction manager per sub-transaction. This PR modifies the 2PC tests for that.
> Create two two-phase commit transaction managers for 2PC tests

- scalardb/src/scalardb/transfer.clj
- scalardb/src/scalardb/transfer_2pc.clj
- scalardb/src/scalardb/transfer_append.clj
- scalardb/src/scalardb/transfer_append_2pc.clj
- scalardb/test/scalardb/transfer_2pc_test.clj
- scalardb/test/scalardb/transfer_append_2pc_test.clj
- scalardb/test/scalardb/transfer_append_test.clj
- scalardb/test/scalardb/transfer_test.clj
When `UnknownTransactionStatusException` is thrown, we are not sure the transaction is committed or not. In that case, we should return `:info` type. This PR fixes it. Please take a look!
> Should return info type when UnknownTransactionStatusException

- scalardl/project.clj
We are facing `OutOfMemoryError` when running `cd scalardl lein deps` in the CI. This PR fixes this issue. I will add inline comments for the details. Please take a look!
> Fix CI failure

- scalardb/project.clj
After the change in https://github.com/scalar-labs/scalardb/pull/770 in ScalarDB, we need the commons text lib dependency in the ScalarDB Jepsen test. This PR adds it. Please take a look.
> Add commons text lib dependency

- .gitignore
- README.md
- docker/control/Dockerfile
- docker/control/init.sh
- docker/docker-compose.yaml
- docker/node/Dockerfile
- docker/node/init.sh
Add docker files to set up a local test environment easily
Jepsen also has scripts for docker env.
However, it doesn't support arm64, and some configurations aren't required for `scalar-jepsen`.
That's why I made docker scripts for `scalar-jepsen`.
> Add docker scripts

- .circleci/config.yml
- cassandra/project.clj
- scalardb/project.clj
- scalardl/project.clj
- scalardl/src/scalardl/core.clj
There are many changes, but, it should be compatible.
Steady tests worked well.
After this upgrade, I'll refine the nemesis injections.
Ref. https://github.com/jepsen-io/jepsen/releases/tag/v0.3.0
Also, It updated dependencies in `project.clj`.
> Upgrade Jepsen to 0.3.1

- scalardl/src/scalardl/core.clj
- scalardl/test/scalardl/transfer_test.clj
I have increased the retry count to fix [read failure for some of the records](https://scalar-labs.atlassian.net/jira/software/c/projects/DLT/issues/DLT-13517) as instructed in this [comment](https://scalar-labs.atlassian.net/browse/DLT-13517?focusedCommentId=17021). I have used https://github.com/scalar-labs/scalar-jepsen/pull/89 as a reference to increase the retry count.
I have not tested this change completely as the issue occurs rarely on the daily test. I will confirm and close the original bug ticket after checking and confirming the results for at least a month once this PR is merged.
> Increase retry count

- scalardb/src/scalardb/transfer_append.clj
- scalardb/src/scalardb/transfer_append_2pc.clj
To investigate the DB transfer_append tests by checking if the latest age is overwritten with the same value
> Add logs for transfer_append

- scalardb/project.clj
- scalardb/test/scalardb/elle_append_2pc_test.clj
- scalardb/test/scalardb/elle_append_test.clj
- scalardb/test/scalardb/elle_write_read_2pc_test.clj
- scalardb/test/scalardb/elle_write_read_test.clj
- scalardb/test/scalardb/transfer_2pc_test.clj
- scalardb/test/scalardb/transfer_append_2pc_test.clj
- scalardb/test/scalardb/transfer_append_test.clj
- scalardb/test/scalardb/transfer_test.clj
> Use ScalarDB SNAPSHOT versions in ScalarDB Jepsen test

- scalardb/src/scalardb/db_extend.clj
- scalardb/test/scalardb/db_extend_test.clj
Cassandra `properties` doesn't have the contact points. To fix it, `nodes` parameters are set to the contact points.
it happened in #114, but CI passed. (After it was merged, it happened. the schema-loder was changed?)
Set `(:nodes test)` to the contact points
he checkboxes after you have read and understood each item.
> Fix cassandra properties

- cassandra/src/cassandra/core.clj
- scalardb/src/scalardb/core.clj
- scalardl/test/scalardl/cas_test.clj
- scalardl/test/scalardl/transfer_test.clj
Cassandra's table setup failed repeatedly even though the waits were inserted.
This workaround tries Cassandra table setup without the schema loader.
- Add a function to open a Cassandra session
- Restore the Cassandra table setup function
- Convert the schemata to the Cassandra(Alia) format
> Workaround Cassandra table setup issue

- scalardb/src/scalardb/elle_append.clj
When I executed `elle-append` workload in `scalardb` directory, a bunch of IllegalArgumentException happened as follows
```
root@control:/scalar-jepsen/scalardb# lein run test --workload elle-append --nemesis crash --admin join --time-limit 300 --ssh-private-key ~/.ssh/id_rsa
...
2024-02-27 08:33:09,633{GMT}    WARN    [parallel-executor-1] com.scalar.db.transaction.consensuscommit.ParallelExecutor: Failed to run a preparation task. transaction ID: c1b0b7b2-ee3b-4f62-aea2-0dd2b2b30cde
java.lang.IllegalArgumentException: CORE-10017: The column value is not properly specified. Column: TextColumn{name=val, value=2}, Operation: Put{namespace=Optional[jepsen], table=Optional[txn0_1], partitionKey=Key{IntColumn{name=id, value=7, hasNullValue=false}}, clusteringKey=Optional.empty, …
```
> ScalarDB/Fix type-mismatch operation on `val` column in `elle-append`

- cassandra/src/cassandra/nemesis.clj
- cassandra/src/cassandra/runner.clj
- cassandra/test/cassandra/runner_test.clj
- docker/node/Dockerfile
- scalardb/src/scalardb/db/postgre.clj
- scalardb/src/scalardb/db/postgres.clj
- scalardb/src/scalardb/db_extend.clj
- scalardb/src/scalardb/runner.clj
Support PostgreSQL for ScalarDB tests
#113
- Implemented `DbExtension` PostgreSQL
- Coordinated nemesis names
> Add Postgres

- .gitignore
- scalardl/src/scalardl/runner.clj
When I separated Cassandra option function, I forgot to update the DL runner.
- Add Cassandra test's `nemesis-opt-spec` and `admin-opt-spec`
> fix DL runner to use cassandra options

- scalardb/project.clj
- scalardb/src/scalardb/core.clj
- scalardb/src/scalardb/elle_append.clj
- scalardb/src/scalardb/elle_append_2pc.clj
- scalardb/src/scalardb/elle_write_read.clj
- scalardb/src/scalardb/elle_write_read_2pc.clj
- scalardb/src/scalardb/transfer.clj
- scalardb/src/scalardb/transfer_2pc.clj
- scalardb/src/scalardb/transfer_append.clj
- scalardb/src/scalardb/transfer_append_2pc.clj
- scalardb/test/scalardb/core_test.clj
- scalardb/test/scalardb/elle_append_2pc_test.clj
- scalardb/test/scalardb/elle_append_test.clj
- scalardb/test/scalardb/elle_write_read_2pc_test.clj
- scalardb/test/scalardb/elle_write_read_test.clj
- scalardb/test/scalardb/transfer_2pc_test.clj
- scalardb/test/scalardb/transfer_append_2pc_test.clj
- scalardb/test/scalardb/transfer_append_test.clj
- scalardb/test/scalardb/transfer_test.clj
Each worker's ScalarDB transaction service requested transactions one by one though there are multiple workers.
This PR changes the transaction request to execute multiple transactions at once.
We can test concurrent transactions in more practical cases, especially for the group commit.
- Generate multiple transfers with `transfer`
- Set `max-num-txs` to request transactions at once
- Execute transactions in parallel in a worker
- Modify the checkers to confirm the number of succeeded transactions
> Request transfer transactions in parallel

- scalardb/src/scalardb/transfer.clj
- scalardb/src/scalardb/transfer_append.clj
The `get-all` transaction to get all records for the consistency check gets some inconsistency results.
In a Jepsen test, the `final-generator` generates the operation after the main generator finishes, but it doesn't check the completion.
So, `get-all` generated by `final-generator` could start before the all transactions were completed.
They were just a read-only transactions and didn't check the conflict with in-flight transactions.
This PR adds the dummy writes to these `get-all` transactions to check the conflict.
- Add dummy writes and commit to `get-all` transactions
> Add dummy writes for get-all to check the confict

- scalardb/src/scalardb/transfer.clj
- scalardb/src/scalardb/transfer_append.clj
- scalardb/test/scalardb/core_test.clj
In `transfer` and `transfer-append` tests in ScalarDB tests, `get-all` which reads all the final state misbehaved.
The dummy writes were committed even though the read failed due to conflicts. Then the `get-all` transaction was retried.
It caused the unexpected version increasing. That's why the check phase failed.
Daily Jepsen test failed
- Catch the exceptions when transaction reads
> Catch an exception in get-all

- scalardb/README.md
- scalardl/README.md
I noticed there is room to improve the README files under `scalardb` and `scalardl` directories. This PR updates the files.
None
- Add missing necessary option `--ssh-private-key` option to the example command in `scalardb/README.md`
- Without the option, I failed to run the Jepsen test
- (Should I add it to `scalardl/README.md` as well?)
- Replace `Scalar DB` with `ScalarDB` and `Scalar DL` with `ScalarDL`
None
> Update the README files under `scalardb` and `scalardl` directories

- scalardb/src/scalardb/core.clj
- scalardb/test/scalardb/core_test.clj
- scalardb/test/scalardb/transfer_2pc_test.clj
- scalardb/test/scalardb/transfer_append_2pc_test.clj
- scalardb/test/scalardb/transfer_append_test.clj
- scalardb/test/scalardb/transfer_test.clj
Recently, `scalardb.transfer$read_all_with_retry` often failed when there are many records to be lazy-recovered more than the max retry (8). To mitigate the failure, this PR increases the max retry. But just increasing it causes too long wait duration. For instance, increasing the max retry up to 10 will result in 1024 seconds wait. So, this PR also introduces an upper limit of wait duration (32 seconds) since too long retry duration doesn't make sense basically.
With the current retry logic and the max retry, the total wait duration until timeout is 510 seconds.
```
irb(main):006:0> 8.times.inject(0) {|acc, x| acc + 1000 * (2 ** (x + 1))}                                                                                                                                       
=> 510000
``` …
> Improve retry for `scalardb` test

- scalardb/src/scalardb/transfer.clj
- scalardb/test/scalardb/transfer_test.clj
To analyze a test failure in details, add more logs for each transaction
- Added a log message
> Add a log for each transfer transaction

- .github/workflows/build-test.yml
- scalardb/project.clj
- scalardl/project.clj
We are encountering the following errors while running the ScalarDB and ScalarDL tests:
ScalarDB:
```java
ERROR [2024-12-18 10:13:47,560] main - jepsen.cli Oh jeez, I'm sorry, Jepsen broke. Here's why:
java.lang.NoClassDefFoundError: org/apache/commons/lang3/function/FailableSupplier
at org.apache.commons.text.lookup.InetAddressStringLookup.<clinit>(InetAddressStringLookup.java:46)
at org.apache.commons.text.lookup.StringLookupFactory.localHostStringLookup(StringLookupFactory.java:1130)
at org.apache.commons.text.lookup.DefaultStringLookup.<clinit>(DefaultStringLookup.java:107)
at org.apache.commons.text.lookup.StringLookupFactory$DefaultStringLookupsHolder.createDefaultStringLookups(StringLookupFactory.java:291)
at org.apache.commons.text.lookup.StringLookupFactory$DefaultStringLookupsHol …
```
> Exclude commons-lang3 lib from Cassandra dependency in ScalarDB and ScalarDL tests

- scalardl/project.clj
In addition to https://github.com/scalar-labs/scalar-jepsen/pull/134, we needed to exclude the `commons-lang3` lib from the `hayt` dependency in the ScalarDL test. This PR addresses it. 
- https://github.com/scalar-labs/scalar-jepsen/pull/134
- Excluded the `commons-lang3` lib from the `hayt` dependency in ScalarDL test.
N/A
> Exclude commons-lang3 lib from hayt dependency in ScalarDL test

- scalardb/src/scalardb/db_extend.clj
- scalardb/src/scalardb/runner.clj
- scalardb/test/scalardb/db_extend_test.clj
- scalardb/test/scalardb/elle_append_2pc_test.clj
- scalardb/test/scalardb/elle_append_test.clj
- scalardb/test/scalardb/elle_write_read_2pc_test.clj
- scalardb/test/scalardb/elle_write_read_test.clj
This PR removes the serializable strategy config, as it was removed in https://github.com/scalar-labs/scalardb/pull/2597.
- https://github.com/scalar-labs/scalardb/pull/2597
- Removed the serializable strategy config.
N/A
> Remove serializable strategy config

- scalardb/src/scalardb/transfer.clj
- scalardb/src/scalardb/transfer_append.clj
When read fails in the `get-all`, some results were used without retry.
It was caused by retrying the read/scan for each ID.
- Retry `get-all` for all IDs with a single transaction
> Fix to retry read-all/scan-all for all IDs

- scalardb/src/scalardb/db_extend.clj
- scalardb/src/scalardb/runner.clj
This PR adds support for the `READ-COMMITTED` isolation introduced by https://github.com/scalar-labs/scalardb/pull/2803.
- https://github.com/scalar-labs/scalardb/pull/2803
- Fixed the validation for the isolation level.
- Added a string conversion for the isolation level.
N/A
> Support READ-COMMITTED isolation

- scalardb/src/scalardb/db_extend.clj
- scalardb/src/scalardb/runner.clj
This PR adds support for one-phase commit optimization introduced by https://github.com/scalar-labs/scalardb/pull/2811.
- https://github.com/scalar-labs/scalardb/pull/2811
- Added support for one-phase commit optimization.
N/A
> Support one-phase commit optimization

- scalardb/src/scalardb/db/cluster.clj
- scalardb/src/scalardb/db_extend.clj
- scalardb/src/scalardb/transfer.clj
- scalardb/test/scalardb/transfer_2pc_test.clj
- scalardb/test/scalardb/transfer_test.clj
After the change in https://github.com/scalar-labs/scalardb/pull/2798, when an uncommitted record is read, the `UncommittedRecordException` is no longer thrown immediately if the corresponding coordinator record exists, and then, lazy recovery is performed asynchronously.
The current `read-all` logic in the transfer test uses the Storage API and relies on the previous behavior where the exception was thrown immediately upon reading an uncommitted record. This approach is incompatible with the new read logic.
To address this issue, this PR updates the `read-all` logic to use the `include_metadata` configuration (`scalar.db.consensus_commit.include_metadata.enabled`) in Consensus Commit to include transaction metadata in the records, instead of relying on the Storage API.
- …
> Use include_metadata configuration in Consensus Commit

- .github/workflows/build-test.yml
- .github/workflows/cluster-test.yml
- .github/workflows/daily.yml
- .github/workflows/test.yml
- scalardb/project.clj
- scalardb/src/scalardb/db/cassandra.clj
- scalardb/src/scalardb/db/cluster.clj
- scalardb/src/scalardb/db/postgres.clj
- scalardb/src/scalardb/db_extend.clj
- scalardb/src/scalardb/runner.clj
- scalardb/test/scalardb/db_extend_test.clj
Remove the dependency scalar-jepsen/cassandra `0.1.0-SNAPSHOT` for tests without Cassandra.
The dependency is required even if a test doesn't use Cassandra for now.
It is a bit confusing and it also takes `lein install` step for all tests.
- Add the `cassandra` profile
- Import the dependency only when using Cassandra
> Separate Cassandra deps

- .github/workflows/cluster-test.yml
- .github/workflows/daily.yml
- scalardb/src/scalardb/db/cluster.clj
Add options to enable `READ_COMMITTED` and `one phase commit` to ScalarDB test workflows
- Add `READ_COMMITTED` isolation level to the daily and the dispatched test
- Set `--enable-one-phase-commit` option for the daily and the dispatched test
> Add options for ScalarDB test workflows

- scalardb/project.clj
- scalardl/project.clj
Since we switched the snapshot repository used for uploading SNAPSHOT versions in ScalarDL (https://github.com/scalar-labs/scalardl/pull/194) and ScalarDB (https://github.com/scalar-labs/scalardb/pull/2849), we should also update the repository reference accordingly. This PR addresses that.
- https://github.com/scalar-labs/scalardl/pull/194
- https://github.com/scalar-labs/scalardb/pull/2849
- Updated the snapshot repository references.
N/A
> Update Maven snapshot repository

- scalardb/src/scalardb/transfer.clj
- scalardb/src/scalardb/transfer_2pc.clj
- scalardb/src/scalardb/transfer_append.clj
- scalardb/src/scalardb/transfer_append_2pc.clj
- scalardb/test/scalardb/transfer_append_test.clj
This PR adds logging for the `transfer` and `transfer-append` workloads to improve observability and debugging.
N/A
- Added logging for the `transfer` and `transfer-append` workloads.
N/A
> Add logging for transfer and transfer-append workloads

- scalardb/project.clj
After upgrading the gRPC library from `1.74.0` to `1.75.0` in https://github.com/scalar-labs/scalardb-cluster/pull/1245, we started encountering the following errors in the ScalarDB Cluster Jepsen tests:
<details>
<summary>
Exception1
</summary>
```java
2025-09-20 13:40:57,264{GMT}    WARN    [clojure-agent-send-off-pool-23] scalardb.transfer: Starting a transaction failed
com.scalar.db.exception.transaction.TransactionException: INTERNAL: http2 exception. Transaction ID: 8984e611-49f0-484d-bc56-bbb084029472
at com.scalar.db.cluster.common.RemoteDistributedTransactionService.begin(RemoteDistributedTransactionService.java:132)
at com.scalar.db.cluster.common.RemoteDistributedTransactionService.begin(RemoteDistributedTransactionService.java:97)
at …
```
> Fix Netty dependency conflict
