scalar-labs/scalar-jepsen

scalardb/src/scalardb/core.clj
scalardb/src/scalardb/transfer.clj
scalardb/src/scalardb/transfer_append.clj

https://scalar-labs.atlassian.net/browse/DLT-2553
I've not almost changed the code logically.
- Collect common processes like table creation
- Add retry macro for checking results
- It will also resolve the existing [issue](https://scalar-labs.atlassian.net/browse/DLT-2634)

Refactor scalardb tests

---

.circleci/config.yml
cassandra/project.clj
cassandra/src/cassandra/batch.clj
cassandra/src/cassandra/collections/map.clj
cassandra/src/cassandra/collections/set.clj
cassandra/src/cassandra/conductors.clj
cassandra/src/cassandra/core.clj
cassandra/src/cassandra/counter.clj
cassandra/src/cassandra/lwt.clj
cassandra/src/cassandra/nemesis.clj
cassandra/src/cassandra/runner.clj
cassandra/test/cassandra/batch_test.clj
cassandra/test/cassandra/core_test.clj
cassandra/test/cassandra/counter_test.clj
cassandra/test/cassandra/lwt_test.clj
cassandra/test/cassandra/map_test.clj
cassandra/test/cassandra/nemesis_test.clj
cassandra/test/cassandra/runner_test.clj
cassandra/test/cassandra/set_test.clj
scalardb/project.clj
scalardb/src/scalardb/core.clj
scalardb/src/scalardb/runner.clj
scalardb/test/scalardb/scalardb_test.clj
scalardl/project.clj
scalardl/src/scalardl/cassandra.clj
scalardl/src/scalardl/core.clj
scalardl/src/scalardl/runner.clj
scalardl/test/scalardl/scalardl_test.clj

https://scalar-labs.atlassian.net/browse/DLT-2726
https://scalar-labs.atlassian.net/browse/DLT-2749
- Use a test coverage tool `cloverage` to run unit tests
- Made `cassandra-dir` configurable
- Refactoring small stuff
- Removed unneeded functions from Cassandra tests
- Added unit tests

Refactoring cassandra 2nd

---

scalardb/src/scalardb/runner.clj
scalardb/src/scalardb/transfer_append.clj
scalardb/test/scalardb/transfer_append_test.clj

https://scalar-labs.atlassian.net/browse/DLT-2749
- Added unit tests for `transfer-append` test
- Renamed some vars

Add unit tests for transfer-append

---

scalardl/contract/Balance.java
scalardl/contract/Create.java
scalardl/contract/Transfer.java
scalardl/project.clj
scalardl/src/scalardl/cassandra.clj
scalardl/src/scalardl/core.clj
scalardl/src/scalardl/nemesis.clj
scalardl/src/scalardl/runner.clj
scalardl/src/scalardl/transfer.clj
scalardl/test/scalardl/transfer_test.clj

https://scalar-labs.atlassian.net/browse/DLT-3410
~It needs the latest client SDK which hasn't been released yet.~
~Unit tests should fail because the public SDK is old for now.~
~I will update the client SDK version after the latest client SDK is released.~

Add payment transfer test for Scalar DL

---

cassandra/src/cassandra/core.clj
cassandra/test/cassandra/core_test.clj

https://scalar-labs.atlassian.net/browse/DLT-3731

increase the retry time to install java

---

scalardl/src/scalardl/cas.clj
scalardl/src/scalardl/core.clj
scalardl/src/scalardl/transfer.clj

#15
- Add common functions for certificate and contract registration
- Check the response of each registration

check status of registration

---

scalardl/src/scalardl/runner.clj

A test unexpectedly started Cassandra node on a DL server and left it.
The node had a record inserted in the test, then the next test read the record and failed due to inconsistency.
- Fix options to specify nodes
- Modify the initial `:decommissioned` node to avoid starting C* on a DL server by the bootstrapper

modify decommissioned node before starting

---

scalardl/src/scalardl/core.clj

https://scalar-labs.atlassian.net/browse/DLT-4392
- Retry install when a test failed to install JDK

Add retry to install JDK for DL test

---

scalardb/project.clj
scalardb/src/scalardb/core.clj
scalardb/src/scalardb/transfer.clj
scalardb/src/scalardb/transfer_append.clj
scalardb/test/scalardb/core_test.clj
scalardb/test/scalardb/transfer_append_test.clj
scalardb/test/scalardb/transfer_test.clj
scalardl/src/scalardl/core.clj

Update the package based on the changes in [the package refactoring PR](https://github.com/scalar-labs/scalardb/pull/63).
I will merge this PR and right after [the package refactoring PR](https://github.com/scalar-labs/scalardb/pull/63) is merged and the CI of this succeeds.

update the package

---

.circleci/config.yml
scalardl/contract/Balance.java
scalardl/contract/Cas.java
scalardl/contract/Create.java
scalardl/contract/Read.java
scalardl/contract/Transfer.java
scalardl/contract/Write.java
scalardl/project.clj
scalardl/src/scalardl/cas.clj
scalardl/src/scalardl/core.clj
scalardl/src/scalardl/transfer.clj
scalardl/src/scalardl/util.clj
scalardl/test/scalardl/cas_test.clj
scalardl/test/scalardl/transfer_test.clj

https://scalar-labs.atlassian.net/browse/DLT-4802
- Modified handling results and exceptions
- Add unit tests for CAS
- Can use the latest DL and SDK built by myself
After merged, we can run a Jepsen test with jars built by myself with `with-profile +use-jars`

Support the latest DL and SDK

---

cassandra/src/cassandra/conductors.clj
cassandra/src/cassandra/core.clj
cassandra/src/cassandra/runner.clj

https://scalar-labs.atlassian.net/browse/DLT-5528
And, update default C* version

Delete data before bootstrapping

---

cassandra/project.clj
cassandra/src/cassandra/conductors.clj
cassandra/src/cassandra/core.clj
cassandra/src/cassandra/counter.clj
cassandra/src/cassandra/lwt.clj
cassandra/test/cassandra/lwt_test.clj

https://scalar-labs.atlassian.net/browse/DLT-4353
Issue: Out of memory happened in the checking phase of Cassandra LWT test
`independent` generator limits the number of operations for checking

LWT test by using independent

---

scalardl/src/scalardl/core.clj
scalardl/src/scalardl/transfer.clj

https://scalar-labs.atlassian.net/browse/DLT-6380

Add retry for DL test

---

scalardl/src/scalardl/transfer.clj

https://scalar-labs.atlassian.net/browse/DLT-6401
I forgot adding retry to the asset creation in the setup phase.

add retry to asset creation

---

scalardl/src/scalardl/cassandra.clj
scalardl/test/scalardl/cassandra_test.clj

https://scalar-labs.atlassian.net/browse/DLT-6602

ignore when no entry exists

---

cassandra/project.clj
cassandra/src/cassandra/batch.clj
cassandra/src/cassandra/collections/map.clj
cassandra/src/cassandra/collections/set.clj
cassandra/src/cassandra/conductors.clj
cassandra/src/cassandra/core.clj
cassandra/src/cassandra/counter.clj
cassandra/src/cassandra/lwt.clj
cassandra/src/cassandra/runner.clj
cassandra/test/cassandra/batch_test.clj
cassandra/test/cassandra/conductors_test.clj
cassandra/test/cassandra/core_test.clj
cassandra/test/cassandra/counter_test.clj
cassandra/test/cassandra/lwt_test.clj
cassandra/test/cassandra/runner_test.clj
scalardb/project.clj
scalardb/src/scalardb/runner.clj
scalardl/project.clj
scalardl/src/scalardl/runner.clj

https://scalar-labs.atlassian.net/browse/DLT-6391
Jepsen 0.2.1 is required. So, this PR will be merged after releasing 0.2.1.

Support Jepsen 0.2.x

---

scalardl/project.clj

https://scalar-labs.atlassian.net/browse/DLT-8131
We need to fix dependencies since Scalar DL was updated.

Fix dependencies

---

scalardl/src/scalardl/cassandra.clj

https://scalar-labs.atlassian.net/browse/DLT-8692
Update the schema for scalardl testing since the merged auditor PR changes the schema of asset_metadata table.
After this PR is merged, I hope jepsen tests for scalardl works normally.

update the schema

---

cassandra/src/cassandra/nemesis.clj

Some Cassandra nodes could fail to restart when the nemesis teardown (just before getting the last state)
A non-seed node fails to find a seed node when all nodes crash
The nemesis teardown reorders the list of Cassandra nodes to start with a seed node same as the nemesis stop

fix C* nemesis teardown

---

scalardb/src/scalardb/elle_append_2pc.clj
scalardb/src/scalardb/elle_write_read_2pc.clj

fix :consistency-level for 2PC tests

---

scalardb/src/scalardb/core.clj

Currently, we are hitting an issue where `NullPointerException` is happening during reconnecting to a cluster. The current reconnection logic is closing a transaction object (and setting it to NULL) first and trying to reconnect to a cluster (and creating a new transaction object), and then resetting the new one as a transaction object. But in the crash situation, the reconnection takes some more time, but the clients continue invoking the workload with the NULL transaction object. I think that's why `NullPointerException` is happening until the reconnection is done.
In this PR, I change the timing to close transaction objects when reconnecting to a cluster. To be specific, I change the timing to right before the resetting. I think we can mitigate the issue with this change. Please take a …

Change timing to close transaction objects when reconnecting to cluster

---

scalardl/src/scalardl/cas.clj
scalardl/test/scalardl/cas_test.clj

Need to fix the DL CAS test for #74

Fix to give nonce for DL CAS test

---

cassandra/src/cassandra/core.clj

https://scalar-labs.atlassian.net/browse/DLT-13144

Fix timeout for C* boot

---

cassandra/src/cassandra/nemesis.clj

Check :cass-nodes in nemesis targeter

---

scalardl/src/scalardl/core.clj
scalardl/test/scalardl/transfer_test.clj

https://scalar-labs.atlassian.net/browse/DLT-13352
The 8 times retry wasn't enough for the tests.

Fix max times retry count

---

.circleci/config.yml
cassandra/project.clj
scalardb/project.clj
scalardl/project.clj
scalardl/src/scalardl/core.clj

Reverts scalar-labs/scalar-jepsen#93

Revert "Upgrade Jepsen to 0.3.1"

---

scalardl/src/scalardl/core.clj

Wait for Cassandra bootstrapping in DL tests

---

.github/workflows/test.yml

Add tests with docker to CI

---

cassandra/project.clj
scalardb/project.clj
scalardl/project.clj

It would improve the performance and the memory consumption.
https://github.com/jepsen-io/jepsen/releases/tag/v0.3.3

Jepsen 0.3.3

---

scalardb/src/scalardb/core.clj
scalardb/src/scalardb/elle_append.clj
scalardb/src/scalardb/elle_append_2pc.clj
scalardb/src/scalardb/elle_write_read.clj
scalardb/src/scalardb/elle_write_read_2pc.clj
scalardb/src/scalardb/transfer.clj
scalardb/src/scalardb/transfer_2pc.clj
scalardb/src/scalardb/transfer_append.clj
scalardb/src/scalardb/transfer_append_2pc.clj
scalardb/test/scalardb/transfer_2pc_test.clj
scalardb/test/scalardb/transfer_append_2pc_test.clj

Reuse the existing functions in non-2pc tests

Refactoring 2pc tests

---

scalardl/test/scalardl/cas_test.clj
scalardl/test/scalardl/transfer_test.clj

Fixed DL tests because `ClientService` arguments mismatched
Fixed the number of arguments

Fix tests for the latest DL

---

scalardb/src/scalardb/core.clj

> Provide a brief description about **why** this PR is necessary. Be sure to provide context.
> Outline the specific changes made in this pull request. Include relevant details, such as added features, bug fixes, code refactoring, or improvements.

Add more wait befor the table deletion

---

.github/workflows/test.yml
scalardb/src/scalardb/core.clj
scalardb/src/scalardb/db_extend.clj
scalardb/src/scalardb/runner.clj

The custom properties weren't set properly.
- Fixed the custom properties setting
- Added `--enable-group-commit`

Set custom properties and add `--enable-group-commit`

---

.github/workflows/cluster-test.yml
.github/workflows/daily.yml
scalardb/src/scalardb/db/cluster.clj
scalardb/src/scalardb/db_extend.clj

The daily tests failed when the isolation level was serializable.
Need to set the isolation level to the cluster nodes.
- Set the isolation level to the cluster nodes

Fix to set the isolation level

---

.github/workflows/daily.yml
scalardb/project.clj

- Report the results of the daily tests to Slack
- Enable Slack notification

Enable slack report

---

scalardb/project.clj

A test failed due to OOM. I would like to increase the maximum heap size.
- Set the maximum heap size to 4GB

increase heap size

---

scalardb/src/scalardb/db/cluster.clj

Need the cluster configuration to enable `one_phase_commit` or `group_commit` in ScalarDB Cluster test
- Set configurations for `one_phase_commit` or `group_commit` in the cluster config if needed

Can enable one_phase_commit or group_commit
